<a href="https://colab.research.google.com/github/ZuCCuK/CloudStorage/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundementals
0.0


In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import torch
print(torch.__version__)


2.0.0+cu118


# İntroduction to Tensors

### Creating tensors

In [2]:
#scalar

In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim
#Dimension sayısını döndürür

0

In [5]:
scalar.item()
#Tensoru int değeri olarak döndürür

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
matrix = torch.tensor([[9,0],
                       [1,4]])
matrix

tensor([[9, 0],
        [1, 4]])

In [10]:
matrix[0]

tensor([9, 0])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
#Tensros
tensor = torch.tensor([[[0,2,4],
                        [1,3,5],
                        [6,7,8]]])
tensor

tensor([[[0, 2, 4],
         [1, 3, 5],
         [6, 7, 8]]])

In [13]:
tensor.ndim 

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

### Tensor Datatypes

In [15]:
int_32_tensor = torch.tensor ( [3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

####Getting information from tensors

tensors not right data type you can check it by using "tensor.dtype" 

tensors not right shape you can check it by using "tensor.shape"

tenors not on right device you can check it by using "tensor.device"

In [16]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.3852, 0.8406, 0.5133, 0.8410],
        [0.0495, 0.2294, 0.4559, 0.4813],
        [0.9032, 0.9103, 0.0425, 0.8548]])

In [17]:
rand_tensor.dtype
rand_tensor.shape 
rand_tensor.device 

device(type='cpu')

###Manipulatin tensors(tensor operations) 
tensor operations include:
* Addition 
* Subtraction
* Multiplication 
* Division
* Matrix Multiplicilation 

In [18]:
#creating a tensor an add 10 to it
tensor = torch.tensor([12,3,5]) 
tensor+20

tensor([32, 23, 25])

In [19]:
#multiplying a tensor
tensor*10
torch.mul(tensor,10)

tensor([120,  30,  50])

In [20]:
#dividin a tensor
tensor/10

tensor([1.2000, 0.3000, 0.5000])

In [21]:
#it goes on like this

###Matrix multiplication 
two main ways of performing multiplication in neural networks and deep learnign

* Element-Wise multiplication
* Matrix Multiplication (Dot Product)
(3,2)@(2,3)  

In [22]:
 #matrix multiplication 
  
torch.matmul(tensor,tensor)

tensor(178)

In [23]:
tensor=torch.tensor([[1,2,3],
                      [4,5,6]])
ntensor=tensor.reshape(3,2)
ntensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
torch.matmul(tensor,ntensor) 
tensor @ ntensor

tensor([[22, 28],
        [49, 64]])

In [26]:
ntensor @ tensor

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

###Finding the min,max,mean,sum,etc(Tensor aggregation)

In [27]:
x = torch.arange(0,100)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

x.min()
torch.min(x)

In [29]:
x.max()
torch.max(x)

tensor(99)

In [34]:
#Find the mean
torch.mean(x)
#tensors datatype is not match 

RuntimeError: ignored

In [33]:
x.dtype

torch.int64

In [31]:
torch.mean(x.type(torch.float32))

tensor(49.5000)

In [36]:
#returns the index of min and max values
torch.argmin(x)
torch.argmax(x)

tensor(99)

##Reshaping, stacking, squeezing, unsqueezing tensors

reshaping - reshapes an input tensor to defined shape

view - return a view of an input tensor of certain shape but keep the same memory at the original tensor 

stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack) 

squeeze - remove all 1 dimensions from a tensor

unsqueeze - add a 1 dimension to a target tensor

permute - return a view of the input with dimensions permuted (swaapped) in a certain way

In [40]:
import torch 
x = torch.arange(0,10)
x.shape  

torch.Size([10])

In [45]:
 #adding extra dimensions
 xr = x.reshape(5,2)
 xr,xr.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]))

In [49]:
 #change the view
 x =  x.view(1,10)
 x,x.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [54]:
#stack tensor on top of each other 
x = torch.arange(0,20,4)
xs = torch.stack([x,x,x,x],dim= 1)
xs

tensor([[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8],
        [12, 12, 12, 12],
        [16, 16, 16, 16]])

In [55]:
xs = torch.stack([x,x,x,x],dim= 0)
xs

tensor([[ 0,  4,  8, 12, 16],
        [ 0,  4,  8, 12, 16],
        [ 0,  4,  8, 12, 16],
        [ 0,  4,  8, 12, 16]])

In [77]:
#squeeze removes all 1 dimensions from  a tensor
x = torch.arange(1,10)
x.shape
x = x.reshape(1,9)

In [78]:
# torch.squeeze ( ) - removes all single dimensions from a target tensor
print (f"Previous tensor: {x}")
print (f"Previous shape: {x.shape}")
# Remove extra dimensions from _reshaped
xs = x.squeeze()
print(f"\nNew tensor{xs}")
print(f"New shape {xs.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensortensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape torch.Size([9])


In [81]:
#unsqueeze - adds a single dimension to a tatget tensor at a spesific dim
print(f"previus tensor: {xs}")
print(f"previus tensor shape: {xs.shape}")
#add an extra dimension by using unsqueeze
xu = xs.unsqueeze(dim=0)
print(f"\nNew tensor: {xu}")
print(f"New tensor shape: {xu.shape}")


previus tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
previus tensor shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New tensor shape: torch.Size([1, 9])


In [83]:
xu = xs.unsqueeze(dim=1)
xu,xu.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [88]:
#permute - rearanges the dimensions of a target tensor in a spesified order
x = torch.rand(size=(224,200,3))
xp = x.permute(2,0,1)
print(f"previus shape: {x.shape}")
print(f"new shape{xp.shape}")

previus shape: torch.Size([224, 200, 3])
new shapetorch.Size([3, 224, 200])


In [89]:
#3,23