<a href="https://colab.research.google.com/github/ZuCCuK/CloudStorage/blob/main/Torch00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundementals
0.0


In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import torch
print(torch.__version__)


2.0.0+cu118


# İntroduction to Tensors

### Creating tensors

In [ ]:
#scalar

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
#Dimension sayısını döndürür

0

In [ ]:
scalar.item()
#Tensoru int değeri olarak döndürür

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[9,0],
                       [1,4]])
matrix

tensor([[9, 0],
        [1, 4]])

In [ ]:
matrix[0]

tensor([9, 0])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensros
tensor = torch.tensor([[[0,2,4],
                        [1,3,5],
                        [6,7,8]]])
tensor

tensor([[[0, 2, 4],
         [1, 3, 5],
         [6, 7, 8]]])

In [ ]:
tensor.ndim 

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

### Tensor Datatypes

In [ ]:
int_32_tensor = torch.tensor ( [3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

####Getting information from tensors

tensors not right data type you can check it by using `tensor.dtype` 

tensors not right shape you can check it by using `tensor.shape`

tenors not on right device you can check it by using `tensor.device`

In [ ]:
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.6780, 0.8894, 0.2853, 0.3417],
        [0.1636, 0.0289, 0.2909, 0.7516],
        [0.2611, 0.3773, 0.8227, 0.8305]])

In [ ]:
rand_tensor.dtype
rand_tensor.shape 
rand_tensor.device 

device(type='cpu')

###Manipulatin tensors(tensor operations) 
tensor operations include:
* Addition 
* Subtraction
* Multiplication 
* Division
* Matrix Multiplicilation 

In [ ]:
#creating a tensor an add 10 to it
tensor = torch.tensor([12,3,5]) 
tensor+20

tensor([32, 23, 25])

In [ ]:
#multiplying a tensor
tensor*10
torch.mul(tensor,10)

tensor([120,  30,  50])

In [ ]:
#dividin a tensor
tensor/10

tensor([1.2000, 0.3000, 0.5000])

In [ ]:
#it goes on like this

###Matrix multiplication 
two main ways of performing multiplication in neural networks and deep learnign

* Element-Wise multiplication
* Matrix Multiplication (Dot Product)
(3,2)@(2,3)  

In [ ]:
 #matrix multiplication 
  
torch.matmul(tensor,tensor)

tensor(178)

In [ ]:
tensor=torch.tensor([[1,2,3],
                      [4,5,6]])
ntensor=tensor.reshape(3,2)
ntensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.matmul(tensor,ntensor) 
tensor @ ntensor

tensor([[22, 28],
        [49, 64]])

In [ ]:
ntensor @ tensor

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

###Finding the min,max,mean,sum,etc(Tensor aggregation)

In [ ]:
x = torch.arange(0,100)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
x.max()
torch.max(x)

tensor(99)

In [ ]:
#Find the mean
torch.mean(x)
#tensors datatype is not match 

RuntimeError: ignored

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32))

tensor(49.5000)

In [ ]:
#returns the index of min and max values
torch.argmin(x)
torch.argmax(x)

tensor(99)

##Reshaping, stacking, squeezing, unsqueezing tensors

reshaping - reshapes an input tensor to defined shape

view - return a view of an input tensor of certain shape but keep the same memory at the original tensor 

stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack) 

squeeze - remove all 1 dimensions from a tensor

unsqueeze - add a 1 dimension to a target tensor

permute - return a view of the input with dimensions permuted (swaapped) in a certain way

In [ ]:
import torch 
x = torch.arange(0,10)
x.shape  

torch.Size([10])

In [ ]:
 #adding extra dimensions
 xr = x.reshape(5,2)
 xr,xr.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]))

In [ ]:
 #change the view
 x =  x.view(1,10)
 x,x.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
#stack tensor on top of each other 
x = torch.arange(0,20,4)
xs = torch.stack([x,x,x,x],dim= 1)
xs

tensor([[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8],
        [12, 12, 12, 12],
        [16, 16, 16, 16]])

In [ ]:
xs = torch.stack([x,x,x,x],dim= 0)
xs

tensor([[ 0,  4,  8, 12, 16],
        [ 0,  4,  8, 12, 16],
        [ 0,  4,  8, 12, 16],
        [ 0,  4,  8, 12, 16]])

In [ ]:
#squeeze removes all 1 dimensions from  a tensor
x = torch.arange(1,10)
x.shape
x = x.reshape(1,9)

In [ ]:
# torch.squeeze ( ) - removes all single dimensions from a target tensor
print (f"Previous tensor: {x}")
print (f"Previous shape: {x.shape}")
# Remove extra dimensions from _reshaped
xs = x.squeeze()
print(f"\nNew tensor{xs}")
print(f"New shape {xs.shape}")

Previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensortensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
New shape torch.Size([9])


In [ ]:
#unsqueeze - adds a single dimension to a tatget tensor at a spesific dim
print(f"previus tensor: {xs}")
print(f"previus tensor shape: {xs.shape}")
#add an extra dimension by using unsqueeze
xu = xs.unsqueeze(dim=0)
print(f"\nNew tensor: {xu}")
print(f"New tensor shape: {xu.shape}")


previus tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
previus tensor shape: torch.Size([9])

New tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New tensor shape: torch.Size([1, 9])


In [ ]:
xu = xs.unsqueeze(dim=1)
xu,xu.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
#permute - rearanges the dimensions of a target tensor in a spesified order
x = torch.rand(size=(224,200,3))
xp = x.permute(2,0,1)
print(f"previus shape: {x.shape}")
print(f"new shape{xp.shape}")

previus shape: torch.Size([224, 200, 3])
new shapetorch.Size([3, 224, 200])


##indexing (selecting data from tensors)
(pretty similar to the numpy so i skipipng this)

##Pytorch tensors &  NumPy

NumPy is a popular scientific Python numerical computing library.

Pytorch has functionality to interact with it 

Data in NumPy, want in PyTorh -> `torch.from_numpy(ndarray)`

PyTorch -> NumPy -> `torch.Tensor.numpy()`


 

In [ ]:
#numpy array to tensor 
import torch
import numpy as np 

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #when converting from numpy to  pytorch, pytorch reflects numpys's default dtype of float64 unless spesified otherwise
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
 #tensor to numpy
 tensor = torch.ones(7)
 np_tensor = tensor.numpy()
 np_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
np_tensor.dtype,tensor.dtype


(dtype('float32'), torch.float32)

## Reproducbility (try to take random out of random)

how a neural network run: 

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> ......`

to reduce the randomness in neural networks and torch comes the concept of a **random seed**.
Essentially what the random seed does is flavour the randomness

In [ ]:


import torch
t1 = torch.rand(3,4)
t2 = torch.rand(3,4)
print(t1)
print(t2)
print(t1==t2)

tensor([[0.1691, 0.3833, 0.1546, 0.2029],
        [0.2581, 0.4183, 0.0079, 0.0586],
        [0.4847, 0.0849, 0.2440, 0.2211]])
tensor([[0.8240, 0.1895, 0.2607, 0.0146],
        [0.1705, 0.8021, 0.5413, 0.1389],
        [0.6255, 0.3653, 0.8193, 0.3567]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
 #lets make some random but reproducible tensors
 import torch

 #set random seed
randomSeed = 43
torch.manual_seed(randomSeed)
t3 = torch.rand(3,4)

torch.manual_seed(randomSeed)
t4 = torch.rand(3,4)

print(t3)
print(t4)
print(t3 == t4)
   

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##GPU

In [ ]:
 import torch
 torch.cuda.is_available()

True

In [ ]:
#setup device with a agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
#count number of device 
torch.cuda.device_count()

1

## Putting tensors, Models on the GPU

In [ ]:
tensor =  torch.tensor([1,2,3],device = "cpu")#or cuda

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to gpu (if available)
gpuTensor = tensor.to(device)
gpuTensor

tensor([1, 2, 3], device='cuda:0')

In [ ]:
 #moving tensors back tp cpu
 gpuTensor.numpy()   #numpy doesnt work with gpu
 

TypeError: ignored

In [ ]:
cpuTensor=gpuTensor.cpu()
cpuTensor.numpy()

array([1, 2, 3])